apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  labels:
    app.kubernetes.io/name: image-updater
    app.kubernetes.io/managed-by: kustomize
  name: image-updater-005
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "*-01"
      images:
        - alias: "guestbook"
          imageName: "quay.io/dkarpele/my-guestbook:~1.0"
          commonUpdateSettings:
            updateStrategy: "semver"
