apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: specs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: "https://10.42.0.1:30003/testdata.git"
        revision: master
        directories:
          - path: 010-appset/cluster-addons/*
        pathParamPrefix: app
       # values:
       #   region: "{{index .path.segments 0}}"
       #   environment: "{{index .path.segments 3}}"
  template:
    metadata:
      name: '{{ .app.path.basename }}'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: fake-webserver=gcr.io/heptio-images/ks-guestbook-demo:0.2
        argocd-image-updater.argoproj.io/fake-webserver.update-strategy: digest
        # argocd-image-updater.argoproj.io/fake-webserver.allow-tags: regexp:^main-
        argocd-image-updater.argoproj.io/fake-webserver.force-update: "true"
        argocd-image-updater.argoproj.io/fake-webserver.ignore-tags: regexp:^sha256
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/fake-webserver.helm.image-name: containers.fake-webserver.image
        argocd-image-updater.argoproj.io/fake-webserver.helm.image-tag: containers.fake-webserver.tag
        argocd-image-updater.argoproj.io/git-repository: https://10.42.0.1:30003/testdata.git
        argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/{{ .app.path.path }}/values.yaml"
        notifications.argoproj.io/subscribe.app-deployed.github: ""
        argocd-image-updater.argoproj.io/git-branch: master
    #      finalizers:
    #        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      sources:
        - repoURL: https://10.42.0.1:30003/testdata.git
          targetRevision: master
          ref: values
        - repoURL: https://github.com/dkarpele/image-updater-examples.git
          path: ./010-appset/cluster-addons/helm1
          targetRevision: "HEAD"
          helm:
            valueFiles:
              - "$values/{{ .app.path.path }}/values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
#      syncPolicy:
#        automated:
#          prune: true
#        syncOptions:
#          - CreateNamespace=true
#          - ServerSideDiff=false
#          - ServerSideApply=false
