apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-001
      component: argocd
  template:
    metadata:
      labels:
        app: test-app-001
        component: argocd
    spec:
      containers:
      - name: test-nginx
        image: nginx:1.17.0

