apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/parent-name: "e2e-registry"
    argocd.argoproj.io/parent-kind: "Deployment"
    argocd.argoproj.io/parent-api-version: "apps/v1"
    argocd.argoproj.io/parent-namespace: "argocd"
  name: e2e-001-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: e30K
